#!/bin/bash

if [ "$1" == "build" ]; then
    mkdir out > /dev/null 2>&1
    tsc src/github-api.ts
    tsc src/graphql.ts
    tsc src/npmjs-api.ts
    tsc src/scorecard.ts
    tsc src/contributors.ts
    tsc src/Version.ts

elif [ "$1" == "install" ]; then
    npm install

elif [ "$1" == "test" ]; then
    npm install
    ./run build
    python3 src/CLI.py "test/sample.txt"
    pip install pytest-cov
    python3 -m pytest --cov=test_suite
    rm -r out/*
    rm -r src/*.js

else
    ./run build
    python3 src/CLI.py $1
    rm -r out/*
    rm -r src/*.js
fi
