#!/bin/bash

{
    IFS=$'\n' read -r -d '' CAPTURED_STDERR;
    IFS=$'\n' read -r -d '' CAPTURED_STDOUT;
} < <((printf '\0%s\0' "$(./helper_run $1)" 1>&2) 2>&1)

if [ "$LOG_LEVEL" = "0" ]; then
    echo "No logging!" > /dev/null 2>&1
elif [ "$LOG_LEVEL" = "1" ]; then
    echo "${CAPTURED_STDOUT}" > "logs/log.txt"
elif [ "$LOG_LEVEL" = "2" ]; then
    echo "${CAPTURED_STDOUT}" > "logs/log.txt"
    echo "${CAPTURED_STDERR}" > "logs/log.txt"
fi